version: '3'
services:

  agent:
    # The default image is set to the static one
    image: ${AGENT_IMAGE:-containers.instana.io/instana/release/agent/static:latest}
    # image: containers.instana.io/instana/release/agent/static:latest
    # To use the dynamic agent (for example, to test the latest Java version), use this image instead:
    # image: instana/agent:latest
    pid: "host"
    privileged: true
    volumes:
      - /var/run:/var/run
      - /run:/run
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
      # Mount the logs directly so we can directly access the span-*.log files to check the produced spans.
      # - ./agent/logs:/opt/instana/agent/data/log
      - ${INSTANA_AGENT_LOGS_VOLUME:-./agent/logs}:/opt/instana/agent/data/log
      - ./agent-configuration/com.instana.agent.main.sender.File.cfg:/opt/instana/agent/etc/instana/com.instana.agent.main.sender.File.cfg
    environment:
      - INSTANA_AGENT_ENDPOINT=${INSTANA_AGENT_ENDPOINT}
      - INSTANA_AGENT_ENDPOINT_PORT=${INSTANA_AGENT_ENDPOINT_PORT}
      - INSTANA_AGENT_KEY=${INSTANA_AGENT_KEY}
      - INSTANA_DOWNLOAD_KEY=${INSTANA_DOWNLOAD_KEY}
      - INSTANA_AGENT_ZONE=${INSTANA_AGENT_ZONE}
      - INSTANA_MVN_REPOSITORY_FEATURES_PATH=artifactory/features-internal@id=features@snapshots@snapshotsUpdate=always
      - INSTANA_MVN_REPOSITORY_SHARED_PATH=artifactory/shared@id=shared@snapshots@snapshotsUpdate=always
      - INSTANA_LOG_LEVEL=DEBUG
    expose:
      - "42699"

#networks:
#  robot-shop:

networks:
  default:
    external:
      #name: robot-shop
      name: robot-shop_robot-shop
